access_control:
  default_policy: deny
  rules:
    - domain:
        - "{{ NGINX_ROOT_DOMAIN }}"
        - "*.{{ NGINX_ROOT_DOMAIN }}"
      subject:
        - "group:admins"
        - "group:lldap_admin"
      policy: two_factor
