services:
  nginx:
    volumes:
      - '{{ (APP_PATH/"conf.d") | mkdir | chown }}:/etc/nginx/conf.d'
    ports:
      - '{{ NGINX_HTTP_PORT }}:{{ NGINX_HTTP_PORT }}'
#     {% if NGINX_HTTPS_ENABLE %}
      - '{{ NGINX_HTTPS_PORT }}:{{ NGINX_HTTPS_PORT }}'
#     {% endif %}
    networks:
      - nginx

networks:
  nginx:
